### PR TITLE
Add user-friendly way to add custom css

### PR DESCRIPTION
**Pull request by colemanw**
Adds an easy gui button in **Administer -> System Settings -> Resource URLs** for the shoreditch custom css file.

shoreditchcss

### CODE REVIEW

**Comment by colemanw** [comment]
FYI @guanhuan

**Comment by AkA84** [comment]
@colemanw please provide a description to the PR explaining what it contains, with screenshots, thanks

**Comment by colemanw** [comment]
@AkA84 done

**Comment by AkA84** [comment]
@colemanw is this something that every future theme will be expected to have? I remember from conversation with @totten that there plans to have a "proper" support for themes selection in CiviCRM, any updates on that?

**Comment by colemanw** [comment]
We absolutely could add a nicer theme selection form to core. This is 
admittedly hacky but works for now.

Once more theme extensions start popping up we can & should go for a 
more robust solution.

**Pull request merged**
