### PR TITLE
Don't overlap civicrm-menu on Wordpress

### PR DESCRIPTION
**Pull request by mik-laj**
Follow: https://github.com/civicrm/civicrm-core/blob/dce0aa6f40bbfab20782d9c61e9f81e05ac5ce58/css/civicrmNavigation.css#L72

### CODE REVIEW

**Comment by mattwire** [comment]
See PR #90.  Not sure why z-index has been added for that selector, it's causing a number of problems and is not defined in the original civicrm.css where it "does the right thing"

**Comment by mik-laj** [comment]
It"s necessary for Wordpress. Wordpress has its own menu that this theme replaces. I will send you a screenshot as I am at home.

**Comment by mattwire** [comment]
@mik-laj If wordpress works ok without the shoreditch theme then I think it will also work with my patch?  As it restores the original behaviour.

**Comment by mik-laj** [comment]
You, are in minor error. Original theme have z-index.
http://i.imgur.com/y447ttx.png
And look at original theme source code:
https://github.com/civicrm/civicrm-core/blob/4.7.25/css/civicrmNavigation.css#L72
I've pasted this link already in another comment
https://github.com/civicrm/org.civicrm.shoreditch/pull/81#issue-263671425 (first messages in this issues)

**Comment by AkA84** [comment]
@mik-laj this had been fixed by https://github.com/civicrm/org.civicrm.shoreditch/pull/270 , please check the PR for additional information

**Comment by mattwire** [comment]
Thanks, tested in Drupal/Wordpress and it does seem to be fixed :-) Raised civicrm/civicrm-core#12632 for Joomla menu issue.

**Pull request closed without merging**
