### PR TITLE
SHOR-146: Use theme system, set shoreditch as backend theme only

### PR DESCRIPTION
**Pull request by AkA84**
## Overview
The soon-to-be-released Civi v5.16 introduced a [theme system](https://docs.civicrm.org/dev/en/latest/framework/theme/), which allows among other things the ability to decide whether to inject the theme in public pages or not, which in turns would solve the issue of style leaks in public pages (see https://github.com/civicrm/org.civicrm.shoreditch/issues/387)

For this reason we are migrating `org.civicrm.shoreditch` from a simple extension to a proper theme

Additional infos: https://lab.civicrm.org/dev/core/issues/378

## Before
public-before

The shoreditch theme is being injected into public pages, causing a style leak

## After
public-after

The shoreditch theme gets defined as a backend theme only, resulting in its stylesheets not being injected into public pages anymore

### Code update
Both `shoreditch.php` and `shoreditch.civix.php` had been changed to use the most up-to-date code that the `civix generate:module` command generates. This was necessary in order to be able to use the new theme system

### Add theme metadata
A `shoreditch.theme.php` file had been added, which contains the theme metadata. The only thing worth mentioning is the `url_callback` property (see below)
```php
return array (
  'name' => 'shoreditch',
  'title' => 'Shoreditch',
  'url_callback' => '_shoreditch_css_url',
  // ...
);
```

### Url callback
A `_shoreditch_css_url` callback (see [here](https://docs.civicrm.org/dev/en/latest/framework/theme/#url_callback)) is being defined, for two reasons:
1. We need to specify that the theme it doesn't want to override the original `civicrm.css`, but rather build on top of it
2. We need to point civi to use the theme's `custom-civicrm.css` stylesheet, otherwise it would look for a `civicrm.css` file that doesn't exist

```php
// Simplified snippet

function _shoreditch_css_url($themes, $themeKey, $cssExt, $cssFile) {
  $urls = array_merge(
    /* 1 */ Civi::service('themes')->resolveUrls('greenwich', $cssExt, $cssFile),
    /* 2 */ \Civi\Core\Themes\Resolvers::simple($themes, $themeKey, $cssExt, 'css/custom-civicrm.css')
  );

  return $urls;
}
```

### Upgrader
An upgraded was added to automatically perform two tasks
1. Remove shoreditch's `custom-civicrm.css` file as the value of the "Custom CSS URL" field
    ```php
    $customCSSUrl = Civi::settings()->get("customCSSURL");
    
    if (strpos($customCSSUrl, 'org.civicrm.shoreditch') !== FALSE) {
      civicrm_api3('setting', 'create', [
        'customCSSURL' => ''
      ]);
    }
    ```
2. Set shoreditch as the backend theme only
    ```php
    civicrm_api3('setting', 'create', [
      'theme_frontend' => 'default',
      'theme_backend' => 'shoreditch'
    ]);
    ```

### CODE REVIEW

**Comment by AkA84** [comment]
@totten I encountered 3 issues while adapting shoreditch to the new theme system, it'd be great if you could take a look, because I'm not sure if there is a problem with the system or if i'm getting something wrong, thanks!

### 1. Missing bootstrap.css
It seems that the `bootstrap.css` file is not being injected automatically. I tried also with a brand new theme and I still couldn't see the file on the page

**Before**
bootstrap-before

This is when the theme was "manually" injecting the file in the page head

```php
function shoreditch_civicrm_coreResourceList(&$items, $region) {
  if ($region == 'html-header') {
    CRM_Core_Resources::singleton()->addStyleFile('org.civicrm.shoreditch', 'css/bootstrap.css', -50, 'html-header');
```

**After**
bootstrap-after

Stylesheet is not injected in the page

### 2. Different file order
It seems that the `civicrm.css` stylesheet of a theme gets injected in a different position than the position the "Custom CSS URL" stylesheet was injected in, causing styling issues in shoreditch

**Before**
import-order-before

`custom-civicrm.css` as "Custom CSS URL" is being injected after `civicrm/css/searchForm.css`

**After**
import-order-after

`custom-civicrm.css` is now being injected before `civicrm/css/searchForm.css`, meaning that the latter overrides the rulesets of the former

### 3. Url callback code
In the [documentation](https://docs.civicrm.org/dev/en/latest/framework/theme/#url_callback), the code to instruct Civi to keep the original `civicrm.css` and just append the theme's afterwards is as follow:

```php
function _newyork_css_url($themes, $themeKey, $cssExt, $cssFile) {
  $urls = \Civi\Core\Themes\Resolvers::simple($themes, $themeKey, $cssExt, $cssFile);
  switch ("{$cssExt}/{$cssFile}") {
    case 'civicrm/css/civicrm.css':
      $urls = array_merge(
        Civi::service('themes')->resolveUrls('greenwich', $cssExt, $cssFile),
        $urls
      );
  }
  return $urls;
}
```
That unfortunately didn't work for me: while `$urls` was indeed made up of both greenwhich's and shoreditch's `civicrm.css` files, only the latter got injected into the page

I thought that maybe civi didn't like that both files had the same name, and in fact once i kept `custom-civicrm.css` as the shoreditch's file, then it worked
```php
function _shoreditch_css_url($themes, $themeKey, $cssExt, $cssFile) {
  switch ("{$cssExt}/{$cssFile}") {
    case 'civicrm/css/civicrm.css':
      $urls = array_merge(
        Civi::service('themes')->resolveUrls('greenwich', $cssExt, $cssFile),
        \Civi\Core\Themes\Resolvers::simple($themes, $themeKey, $cssExt, 'css/custom-civicrm.css')
      );
      break;
    default:
      $urls = \Civi\Core\Themes\Resolvers::simple($themes, $themeKey, $cssExt, $cssFile);
  }

  return $urls;
}
```

**Comment by totten** [comment]
I've pushed up a few commits which the issues above. More details in commit notes.

**Comment by igorpavlov** [comment]
Rebased with latest master

**Comment by igorpavlov** [comment]
@totten I have reviewed the code, installed a local version of CiviCRM `5.16.0` and can confirm the issues pointed out by @AkA84 are addressed and resolved.

сс @jamienovick

**Comment by jamienovick** [comment]
@totten do you think we will need to test those upgrading from previous versions for this? I think the upgrader probably does the job? @igorpavlov FYI.

**Comment by totten** [comment]
@jamienovick  Well, since there is upgrade logic, it's a good idea to try out an upgrade (if it hasn't been tried otherwise).

:+1: on communicating clearly. 

One mitigating consideration... which doesn't help with folks pulling directly from Github, but... the `info.xml` update (a2f37920999d7f2b5576310bc0a367c9fb7bf30f) should help some other use-cases:

* On https://civicrm.org/extensions/shoreditch the "Releases" table mentions the minimum version.
* For anyone using pre-release feeds for semi-automatic download (`cv dl --dev` or `ext_repo_url`), the feed is filtered on compatibility. So `5.15` sites don't see releases that require `5.16`.

Related: #403

**Pull request merged**
