### PR TITLE
Remove unneeded script after updating icons in core

### PR DESCRIPTION
**Pull request by colemanw**
Following up on https://github.com/civicrm/civicrm-core/pull/12541 - we can now remove this script as the icons are being swapped in core, which will accomplish the same thing.

### CODE REVIEW

**Comment by AkA84** [comment]
hi @colemanw , in what version is https://github.com/civicrm/civicrm-core/pull/12541 included? I cannot find its changes in 5.4.0 despite having been merged before that release

I still see in `civicrmNavigation.css`
```css
img.menu-item-arrow{
  position: absolute;
  right: 4px;
  top: 8px;
}
#civicrm-menu i {
  margin-right: 5px;
}
```

**Comment by seamuslee001** [comment]
@AkA84 As the PR was merged into master at the time rather than 5.4 branch which was in RC at the time, the PR has now been merged into 5.5 release which will go out at the start of September 5.5 is currently in RC

**Comment by AkA84** [comment]
Thanks @seamuslee001 👍  we'll wait for the 5.5 version to go out then before proceeding with this PR

**Comment by christianwach** [comment]
Bump :-)

**Comment by colemanw** [comment]
@AkA84 this should be merged along with #364

**Comment by AkA84** [comment]
@colemanw merging, apologies for the big delay

**Pull request merged**
