### PR TITLE
NDI-4: Styled event dashboard page

### PR DESCRIPTION
**Pull request by mukeshcompucorp**
### Description:
This PR styles 
- event dashboard page.
- membership dashboard page.

#### Before:
before

#### After:
after

#### Before:
before

#### After:
after

### Technical details:
- This PR fixes crm-icons in table and dropdown for for contact type (i.e. Individual, Household etc.) https://github.com/civicrm/org.civicrm.shoreditch/pull/95/files#diff-5badf14ccdff391c5b582a16a99e8412

### Notes:
- [x] browserstack tested
- [x] Backstop tested

Color palette changes are covered in https://github.com/civicrm/org.civicrm.shoreditch/pull/94

### CODE REVIEW

**Comment by jamienovick** [comment]
@mukeshcompucorp do you think you can make the event summary title and the recent registrations titles look like part of the tables beneith them and use the grey header background? Examples: https://www.awesomescreenshot.com/image/2943612/3b4b33ad9570545ee2c8dbaa4b92364b

Can you do the same for contributions and other dashboard pages?

**Comment by mukeshcompucorp** [comment]
@jamienovick yes, that can be done as well currently it's as per /civicrm/member?reset=1
should we make member dashboard as well like that? I can make some common CSS in that case for all such headers

**Comment by jamienovick** [comment]
@jonscreat ^

**Comment by jamienovick** [comment]
@jonscreat can you take it from here?

Yes it should be the same for all of the dashboards (and all tables basically) (i.e. Contributions, membership, events and pledges) and also for all of the tables on the contact record.

We should not have these floating headers/titles for tables. 

In some cases we have some descriptive text in between the title and the table, but we should still have one table and just have the descriptive text also in the header in a green box. Does that make sense?

**Comment by mukeshcompucorp** [comment]
Yeah, that makes sense. I will change accordingly on all places.

**Comment by JonScreat** [comment]
Just for clarity, we shouldn't ever have these floating headers per the styleguide.

If it's a page title it should be 'attached' to the top of the page and if it's a panel header then it should be attached to the body of the panel. 

See here for reference: https://projects.invisionapp.com/d/main#/console/10432973/221634721/preview

**Pull request merged**
