### PR TITLE
SHOR-77: Increase specificity for .status-overdue color

### LINKED ISSUE #242: "warning labels and messages" style rules overridden
The highlighting of overdue or scheduled activities is gone due to more specific rules within the shoreditch stylesheet, e.g. in
```CSS
.page-civicrm-contact #mainTabContainer .crm-activity-selector-activity div[id*="DataTables_Table_"] table.dataTable>tbody>tr>td {
    /* ... */
    color: #4D4D69;
    /* ... */
}
```
This is the original style declaration with the color highlighting:
```CSS
.crm-container del, .crm-container .crm-is_deleted, .crm-container table.caseSelector td.status-urgent, .crm-container .font-red, .crm-container .status-removed, .crm-container .status-overdue, .crm-container .status-fatal, .crm-container .status-hold, .crm-container .status-past, .crm-contact-deceased, .crm-container .status-warning {
    color: #E43D2B !important;
}
```
This should be extended to include subsequent elements as well, so that they are only overridden if there is a more specific rule:
```CSS
.crm-container del *,
.crm-container .crm-is_deleted *,
.crm-container table.caseSelector td.status-urgent *,
.crm-container .font-red *,
.crm-container .status-removed *,
.crm-container .status-overdue *,
.crm-container .status-fatal *,
.crm-container .status-hold *,
.crm-container .status-past *,
.crm-contact-deceased *,
.crm-container .status-warning * {
  color: #E43D2B;
}
```
Note the missing `!important` so that deliberately overriding is still possible.

Also, this is not tested in scenarios other than the activity list.

I just inspected the generated CSS, so unfortunately I can't provide a patch for the SCSS.

### PR DESCRIPTION
**Pull request by AkA84**
Closes #242 , which also contains a nice in-depth analysis with screenshots in [this comment](https://github.com/civicrm/org.civicrm.shoreditch/issues/242#issuecomment-415447188)

Unfortunately I don't see any other way to fix this but to have a selector with stronger specificity. Not only we have our own style causing the issue, but also the seven theme is contributing to it.

After the fix:
after

### CODE REVIEW

**Comment by jensschuppe** [comment]
This seems to cover overdue activities only. However, as pointed out in [#242](https://github.com/civicrm/org.civicrm.shoreditch/issues/242#issue-341004329), the fix needs to address more selectors (from CiviCRM core CSS):

```CSS
.crm-container del,
.crm-container .crm-is_deleted,
.crm-container table.caseSelector td.status-urgent,
.crm-container .font-red,
.crm-container .status-removed,
.crm-container .status-overdue,
.crm-container .status-fatal,
.crm-container .status-hold,
.crm-container .status-past,
.crm-contact-deceased,
.crm-container .status-warning {
    color: #E43D2B !important;
}
```

Also, the fix makes the color rule apply to table cells within a `.contact-activity-selector-activity` element only, which might be ok, if that's the only place where these classes are used, but the original core styles indicate that these classes may be used anywhere within a `.crm-container` element.

**Comment by AkA84** [comment]
@jensschuppe you are right, I should have said explicitly that this PR fixes only the specific issue that you reported in #242 

Researching and troubleshoot all the potential locations that might be affected by seven and/or shoreditch will take much longer, and I wanted to have a quick solution in place in the meantime so that the usability of the Activities tab is not negatively affected by the theme

Sorry for the miscommunication!

**Comment by jensschuppe** [comment]
No need to apologize, and thanks for working on it.

Maybe I didn't point out clearly enough that it's more than just overdue activities (as can be seen in the CSS I posted), and I chose those as an example to illustrate the issue.

For the issue of fixing the other selectors not getting lost, would you open #242 again for more commits or should we open another issue?

**Comment by AkA84** [comment]
sure @jensschuppe , just did

**Pull request merged**
