### PR TITLE
HW-345: Reduce margin

### PR DESCRIPTION
**Pull request by mukeshcompucorp**
**Before**
header-issue

**After**
resolved-header-issue

**Note:** Discussed with @guanhuan  and changed heading design similar to Amnesty.

### CODE REVIEW

**Comment by AkA84** [comment]
@mukeshcompucorp @guanhuan is this something that should be done in CiviCase or in any core screens?

**Comment by mukeshcompucorp** [comment]
@AkA84 It will applicable in all core screens.

**Comment by AkA84** [comment]
@mukeshcompucorp  (cc @guanhuan ) i know that this PR will apply the changes to all core screens, I'm asking if that's what we want though

**Comment by mukeshcompucorp** [comment]
@AkA84 Yes, we need to apply this change to all core screens.

**Comment by AkA84** [comment]
@mukeshcompucorp can you explain to me the content of the last commit?

**Comment by mukeshcompucorp** [comment]
@AkA84 After discussing with @guanhuan we decided to go with the same styling as Amnesty project. 
So, we copied over that style here to make header aligned with breadcrumb.

The changes you are seeing in the style are taken from Amnesty project. See the title (h1) attached to breadcrumb (full width).

**Comment by AkA84** [comment]
@mukeshcompucorp if you need style from amnesty, then you don't need to copy over anything. amnesty's work had been merged into shoreditch a couple of days ago in our fork. please check if all looks correct there

**Pull request closed without merging**
