### PR TITLE
Fix contact summary display

### PR DESCRIPTION
**Pull request by mattwire**
Before:
fix_contact_summary_before
After:
fix_contact_summary_after

Drupal base theme is a customised adaptivetheme

### CODE REVIEW

**Comment by AkA84** [comment]
@mattwire can you give more details on the issue that you fixed? Did it happen only in certain viewport width ranges? Why? Also, did it happen only for certain browsers? Thanks!

**Comment by mattwire** [comment]
Using Chrome 60. Also happens in firefox. Seems to affect all widths.  I'm running a slightly customised version of adaptivetheme on drupal: https://github.com/mattwire/drupal_adaptivetheme_mjwconsulting

It also seems to do the same using "Garland" theme.

**Comment by mattwire** [comment]
Looks like a variant of this has now been merged and the problem resolved.

**Comment by MegaphoneJon** [comment]
@mattwire I'm not sure that a variant HAS been merged.  Are you referring to the merge @davialexandre did on October 6th?  That mistakenly references this issue - Davi merged Compucorp PR 52, not this PR.  Or is there another reason to believe a variant was merged?

I'm running the develop branch and am still seeing this bug.

**Comment by mukeshcompucorp** [comment]
@mattwire can you retest this once again with latest version, this should no longer happen as we have a flexbox solution now with https://github.com/compucorp/org.civicrm.shoreditch/pull/103
so, we can close this

**Comment by mattwire** [comment]
Tested with 0.1alpha17 and drupal bootstrap theme.  Confirmed fixed.

**Pull request closed without merging**
