### PR TITLE
Rebuild civix for PHP 7.4 support

### PR DESCRIPTION
**Pull request by IProSoft**
## Overview
Extension is outdated and throw error in PHP 7.4

## Before
PHP Deprecated: Array and string offset access syntax with curly braces is deprecated

## After
No errors

## Technical Details
Rebuild civix with built in function civix generate:module

### CODE REVIEW

**Comment by IProSoft** [comment]
Is there any chance to review this changes ?

**Comment by IProSoft** [comment]
Is there any chance to review this changes ?

**Comment by olayiwola-compucorp** [comment]
Thanks, @IProSoft. we are looking into this.


Is it possible to upgrade the civix file using the latest version of civix?

**Comment by IProSoft** [comment]
Changes made @olayiwola-compucorp :-)

**Comment by olayiwola-compucorp** [comment]
Great work @IProSoft

**Comment by olayiwola-compucorp** [comment]
Merging this into the workstream branch, which would be used by QA for testing.

**Pull request merged**
